language: node_js
node_js:
  - "8"
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - yarn run build
script:
  - yarn run test
after_success:
  - yarn run coverage
